spring:
  jpa:
    show-sql:  true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  r2dbc:
    url: r2dbc:pool:mysql://20.11.22.159:3306/userresistration
    username: root
    password: root
  application:
    name: USER-LOGIN
  config:
    import: configserver:http://localhost:8086
  webflux:
    base-path: /userlogin
server:
  port: 8085