spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  r2dbc:
    url: r2dbc:pool:mysql://127.0.0.1:3306/userresistration
    username: root
    password: root
  application:
    name: USER-LOGIN
  config:
    import: configserver:http://localhost:8086
  webflux:
    base-path: /userlogin
server:
  port: 8085

management:
  zipkin:
    tracing:
      endpoint: http://localhost:8080/api/v2/spans
  tracing:
    sampling:
      probability: 1.0








#
#spring:
#  jpa:
#    hibernate:
#      ddl-auto: update
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/userresistration
#    username: root
#    password: root
#  application:
#    name: USER-LOGIN
#  config:
#    import: configserver:http://localhost:8086
##eureka:
##  instance:
##    prefer-ip-address: true
##  client:
##    fetch-registry: true
##    register-with-eureka: true
##    service-url:
##      defaultZone: http://localhost:8080/eureka
#server:
#  port: 8085
#  servlet:
#    context-path: /userlogin
#management:
#  zipkin:
#    tracing:
#      endpoint: http://localhost:8080/api/v2/spans
#  tracing:
#    sampling:
#      probability: 1.0
#
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#logging:
#  file:
#    name: "C://Users//Admin//Downloads//logfolder//userlogin_log.log"